pipelines:
    - pipeline 1:
        steps:
            - step 1:
                name: Load Some Table
                description: Loading some table from HDFS into Hive
                action: load
                sources:
                    - source_1:
                        path: hdfs://sea-2671-01.paraport.com/data/extract/factflat/ymd=20180129/factflat.orc
                        format: orc
                        delimiter: ","
                        hasHeaderRow: True
                        columns:
                            - EXTRACT_DATE:
                                position: 1
                                name:
                                datatype: int
                            - SHORT_NAME:
                                position:
                                name: SHORT_NAME
                                datatype: string
                            - HOLDING_IDENTIFIER:
                                position: 3
                                name: Entity Description
                                datatype: string
                            - column value:
                                position:
                                name: QUANTITY
                                datatype: money
                transformations:
                    - transformation_1:
                        action: map
                        source 1: source_1.*
                        source 2:
                        destination 1: destination_1.*
                        destination 2:
                destinations:
                    - destination_1:
                        path: ~/AlexK/output.csv
                        format: csv
                        delimiter: "|"
                        hasHeaderRow: True
                        isPersisted: False
                        mode: overwrite
                        columns:
                            - EXTRACT_DATE:
                                position: 1
                                name: Date of Extraction
                                datatype: int
                            - SHORT_NAME:
                                position: 3
                                name: Name Short
                                datatype: string
                            - HOLDING_IDENTIFIER:
                                position: 2
                                name: Entity Description
                                datatype: string
                            - column value:
                                position: 4
                                name: Sum Qty
                                datatype: money
